baseURL = "https://hannah-e-alex.it/"
languageCode = "en-us"
title = "Wedding Website!"
canonifyURLs = true
relativeUrls = true
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/HA-2.jpg"
  author = "Hannah & Alex"
  description = "Hannah & Alex"
  photo1 = "img/HA-0.jpg"
  photo2 = "img/HA-1.jpg"
  photo3 = "img/HA-2.jpg"

[[deployment.targets]]
name = "mydeployment"
URL = "s3://hannahealex?region=eu-central-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E89UWA22XQWFA"


[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

## Main Menu
[[menu.main]]
  name = "Accomodations"
  weight = 300
  identifier = "blog"
  url = "/accomodations/"
[[menu.main]]
  name = "Useful Information & Links"
  identifier = "projects"
  weight = 200
  url = "/Wedding/"
[[menu.main]]
  name = "Schedule & Locations"
  identifier = "resume"
  weight = 100
  url = "/schedule/"